const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  B2B_WHOLESALER: 'B2B_WHOLESALER',
  ADMIN: 'ADMIN'
};

const B2B_STATUS = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const ORDER_STATUS = {
  PLACED: 'PLACED',
  CONFIRMED: 'CONFIRMED',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  // Extra statuses for future use
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_METHODS = {
  COD: 'COD',
  UPI: 'UPI',
  CARD: 'CARD',
  NETBANKING: 'NETBANKING'
};

const B2B_REQUEST_STATUS = {
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  QUOTED: 'QUOTED',
  CLOSED: 'CLOSED'
};

module.exports = {
  USER_ROLES,
  B2B_STATUS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  B2B_REQUEST_STATUS
};
